### PR TITLE
CPEX 046 v2: Particle extension

### PR DESCRIPTION
**Pull request by AlexandreMinotCSI**
SIDS, FMM and MLL doc in ReST site for CPEX 0046 - particle extension

### CODE REVIEW

**Comment by AlexandreMinotCSI** [comment]
I would like to squash those commits, let me know if that's something that can be done from here of if I have to do it on my side.
Thanks

**Comment by MicK7** [comment]
> I would like to squash those commits, let me know if that's something that can be done from here of if I have to do it on my side. Thanks

The squash can be done from here during the merge but only one commit will remain.

**Comment by MicK7** [comment]
LGTM. I will read it again before merging

**Comment by AlexandreMinotCSI** [comment]
I can't figure out how to fix the check failure. Any ideas?

**Comment by brtnfld** [comment]
Add words to skip in .codespellrc

**Comment by AlexandreMinotCSI** [comment]
Thanks for helping resolve the merge issues. Is this ready to be merged? Anything you need from us?

**Comment by brtnfld** [comment]
We're all set for now. After I finish updating the doxygen entries and pushing them to the new website, I'll review it. This will allow us to update the documentation along with the next CGNS release. The odds are that there will be many conflicts once my changes merge.

**Comment by AlexandreMinotCSI** [comment]
Hi,
Is there a released date planned?
Thanks,
Alex

**Comment by brtnfld** [comment]
We are planning a release by the end of the year.

**Comment by brtnfld** [comment]
I'm in the process of transferring non-doxygen information from the midlevel/*html in PR #6. We no longer use these HTML files since they are now generated from Doxygen, 

https://github.com/CGNS/cgns-modern.github.io/pull/6/files#diff-11e4acab6afe17691a724b6480b229eb97556f121f43c02993e0650808c123c7

These will have to be removed from your PR at some point. The other files that might have conflicts are the MLL/CGNS_MLL* files, which are no longer used.

**Comment by brtnfld** [comment]
@MicK7, I think this needs to be merged so that I can reference some of the documents in my PR. Do you see any reason not to merge it?

**Comment by MicK7** [comment]
> @MicK7, I think this needs to be merged so that I can reference some of the documents in my PR. Do you see any reason not to merge it?

@brtnfld  I don't see any reason not to merge it. Will you remove the MLL "html" files introduced by this PR in yours or should we remove them before merging ?

**Comment by MicK7** [comment]
> > @MicK7, I think this needs to be merged so that I can reference some of the documents in my PR. Do you see any reason not to merge it?
> 
> @brtnfld I don't see any reason not to merge it. Will you remove the MLL "html" files introduced by this PR in yours or should we remove them before merging ?

Merging with the HMTL files. We will handle them afterward

**Review by MicK7 — APPROVED** [review]

**Pull request merged**
